services:
  petshop_database:
    image: mongo:latest
    container_name: petshop_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - petshop_db_data:/data/db
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: petshop_database
      DB_DATABASE: petshop_db
      DB_USER: petshop_user
      DB_PASSWORD: petshop_password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpassword
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    volumes:
      - keycloak_data:/opt/keycloak/data
  keycloak_db:
    image: postgres:latest
    container_name: keycloak_db
    environment:
      POSTGRES_ROOT_PASSWORD: rootpassword
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    
volumes:
  petshop_db_data:
  keycloak_db_data:
  keycloak_data: